// config/industries.js — Single source of truth for industry → sub-specialisation map
// Used by: backend (require), frontend (inlined in register + profile-edit HTML)
// IMPORTANT: If you update this file, also update the inline copies in:
//   - public/register/index.html (var INDUSTRY_SUBS = ...)
//   - public/profile-edit/index.html (var INDUSTRY_SUBS = ...)

const INDUSTRY_SUBS = {
  accounting:       { label: 'Accounting / Taxation / Audit',              subs: ['Accounts Payable', 'Accounts Receivable', 'GST', 'Taxation', 'Bookkeeping', 'Reconciliation'] },
  administration:   { label: 'Administration / Office Management',         subs: ['Executive Assistant', 'Office Manager', 'Receptionist', 'Facilities Management', 'Personal Assistant'] },
  media:            { label: 'Advertising / Media / PR',                   subs: ['Media Planning', 'Public Relations', 'Advertising', 'Corporate Communications', 'Event Management'] },
  architecture:     { label: 'Architecture / Interior Design',             subs: ['Architectural Design', 'Interior Design', 'Urban Planning', 'Landscape Architecture', 'BIM / Revit'] },
  audit:            { label: 'Audit & Assurance',                          subs: ['Internal Audit', 'External Audit', 'SOX Compliance', 'Statutory Audit', 'IS Audit'] },
  aviation:         { label: 'Aviation / Flight Operations / Cabin Crew',  subs: ['Pilot', 'Cabin Crew', 'Airport Operations', 'Air Traffic Control', 'Aircraft Maintenance'] },
  banking:          { label: 'Banking / Financial Services',               subs: ['Retail Banking', 'Trade Finance', 'Loan Processing', 'Credit Analysis', 'NBFC'] },
  civil:            { label: 'Civil / Surveying',                          subs: ['Structural Engineering', 'Geotechnical', 'Quantity Surveying', 'Land Surveying', 'Construction Management'] },
  compliance:       { label: 'Compliance / Regulatory',                    subs: ['KYC', 'AML', 'Transaction Monitoring', 'Sanctions', 'CKYC', 'FATF Compliance'] },
  customer_support: { label: 'Customer Support / Helpdesk / Telecalling',  subs: ['Voice Support', 'Chat Support', 'Email Support', 'Technical Support', 'Customer Success'] },
  cybersecurity:    { label: 'Cybersecurity / InfoSec',                    subs: ['SOC Analyst', 'VAPT', 'InfoSec', 'Penetration Testing', 'Vulnerability Assessment'] },
  data:             { label: 'Data / Analytics / BI',                      subs: ['Data Analysis', 'Business Intelligence', 'Data Engineering', 'Data Science', 'Tableau / Power BI'] },
  engineering:      { label: 'Engineering (General)',                       subs: ['Process Engineering', 'Industrial Engineering', 'Quality Engineering', 'R&D Engineering', 'Project Engineering'] },
  erp_crm:          { label: 'ERP / CRM (IT Software)',                    subs: ['SAP', 'Oracle ERP', 'Salesforce', 'Microsoft Dynamics', 'ServiceNow'] },
  finance:          { label: 'Finance / Treasury',                         subs: ['Treasury', 'Cash Management', 'FP&A', 'Corporate Finance', 'Financial Planning'] },
  fraud:            { label: 'Fraud / Anti-Fraud',                         subs: ['Fraud Analyst', 'AML', 'Chargeback', 'Fraud Investigation', 'Anti-Money Laundering'] },
  freshers:         { label: 'Fresh Graduates / Trainees / Interns',       subs: ['Management Trainee', 'Graduate Engineer Trainee', 'Internship', 'Apprenticeship', 'Campus Recruitment'] },
  government:       { label: 'Government / Public Sector',                 subs: ['Civil Services', 'Municipal Administration', 'Policy Analysis', 'Public Finance', 'Defence Civilian'] },
  design:           { label: 'Graphic / Web / Visual Design',              subs: ['UI/UX Design', 'Graphic Design', 'Web Design', 'Motion Graphics', 'Brand Design'] },
  hse:              { label: 'Health / Safety / Environment (HSE)',         subs: ['Safety Officer', 'Environmental Health', 'NEBOSH', 'Fire Safety', 'Occupational Health'] },
  healthcare:       { label: 'Healthcare / Medical / Paramedical',         subs: ['Nursing', 'Physician', 'Lab Technician', 'Pharmacy', 'Medical Coding'] },
  hospitality:      { label: 'Hospitality / F&B / Housekeeping',           subs: ['Hotel Management', 'Food & Beverage', 'Front Office', 'Housekeeping', 'Chef / Culinary'] },
  hr:               { label: 'Human Resources / People Ops',               subs: ['Talent Acquisition', 'Recruiter', 'HRBP', 'Learning & Development', 'Payroll', 'HR Generalist'] },
  insurance:        { label: 'Insurance / Underwriting / Actuarial',       subs: ['Underwriting', 'Claims Processing', 'Actuarial', 'Reinsurance', 'Insurance Sales'] },
  it:               { label: 'IT / Systems',                               subs: ['System Admin', 'Network Admin', 'IT Support', 'Infrastructure', 'ERP', 'IT Operations'] },
  hardware_it:      { label: 'IT Hardware / Support / Maintenance',        subs: ['Desktop Support', 'Hardware Repair', 'Field Engineer', 'IT Technician', 'CCTV / Security Systems'] },
  content:          { label: 'Journalism / Content / Editing',             subs: ['Content Writing', 'Copywriting', 'Technical Writing', 'Editing', 'Journalism'] },
  translation:      { label: 'Language Translation',                       subs: ['Translation', 'Interpretation', 'Localisation', 'Subtitling', 'Transcription'] },
  legal:            { label: 'Legal / Law / Advisory',                     subs: ['Corporate Law', 'Litigation', 'Contract Management', 'Paralegal', 'Intellectual Property'] },
  supply_chain:     { label: 'Logistics / Supply Chain',                   subs: ['Warehouse Management', 'Inventory Control', 'Distribution', 'Freight / Shipping', 'Procurement Logistics'] },
  marine:           { label: 'Marine / Shipping / Offshore',               subs: ['Merchant Navy', 'Port Operations', 'Ship Management', 'Offshore Operations', 'Maritime Law'] },
  marketing:        { label: 'Marketing / Brand / Digital Marketing',      subs: ['Digital Marketing', 'SEO / SEM', 'Content Marketing', 'Brand Management', 'Growth Marketing'] },
  mech_electrical:  { label: 'Mechanical / Electrical / Plumbing (MEP)',   subs: ['HVAC', 'Electrical Systems', 'Plumbing', 'Maintenance Engineering', 'Electromechanical'] },
  mining:           { label: 'Mining / Drilling / Geology',                subs: ['Mine Planning', 'Geologist', 'Drilling Engineer', 'Blasting', 'Mineral Processing'] },
  oil_gas:          { label: 'Oil & Gas / Energy',                         subs: ['Upstream', 'Downstream', 'Refinery Operations', 'Pipeline Engineering', 'Renewable Energy'] },
  operations:       { label: 'Operations / Back Office',                   subs: ['Business Operations', 'Process Improvement', 'Back Office', 'Vendor Management', 'MIS Reporting'] },
  other:            { label: 'Other',                                      subs: [] },
  pharma:           { label: 'Pharmaceutical / Life Sciences',             subs: ['Clinical Research', 'Regulatory Affairs', 'Drug Safety', 'Pharmacovigilance', 'Quality Assurance'] },
  procurement:      { label: 'Procurement / Purchase / Vendor Management', subs: ['Strategic Sourcing', 'Vendor Management', 'Purchase Management', 'Category Management', 'Contract Negotiation'] },
  product:          { label: 'Product Management',                         subs: ['Product Strategy', 'Product Owner', 'Roadmap Planning', 'User Research', 'Agile / Scrum'] },
  manufacturing:    { label: 'Production / Manufacturing',                 subs: ['Production Planning', 'Plant Operations', 'Lean Manufacturing', 'Six Sigma', 'Quality Control'] },
  qa:               { label: 'Quality / Testing / QA / QC',               subs: ['Manual Testing', 'Automation Testing', 'QA Lead', 'Performance Testing', 'Quality Assurance'] },
  r_and_d:          { label: 'Research & Development',                     subs: ['Research Scientist', 'Lab Research', 'Product Development', 'Innovation', 'Technical Research'] },
  retail:           { label: 'Retail / Store Operations',                  subs: ['Store Manager', 'Visual Merchandising', 'Retail Sales', 'Inventory Management', 'E-commerce Operations'] },
  risk:             { label: 'Risk Management',                            subs: ['Credit Risk', 'Market Risk', 'Operational Risk', 'Basel', 'Risk Analyst'] },
  sales:            { label: 'Sales / Business Development',               subs: ['Inside Sales', 'Field Sales', 'Key Account Management', 'Business Development', 'Channel Sales'] },
  security:         { label: 'Security Services / Guards',                 subs: ['Security Supervisor', 'Loss Prevention', 'Physical Security', 'Access Control', 'CCTV Monitoring'] },
  management:       { label: 'Senior Management / Leadership',             subs: ['CEO / MD', 'VP / Director', 'General Manager', 'Country Head', 'Business Head'] },
  site_engineering: { label: 'Site Engineering / Projects',                subs: ['Site Engineer', 'Project Manager', 'Construction Supervisor', 'Planning Engineer', 'QS / Estimation'] },
  software:         { label: 'Software Development / Engineering',         subs: ['React', 'Node.js', 'Python', 'Java', 'Full Stack Developer', 'Backend', 'Frontend'] },
  network_admin:    { label: 'System / Network Administration',            subs: ['Network Engineer', 'System Administrator', 'Cisco / CCNA', 'Cloud Infrastructure', 'DevOps'] },
  education:        { label: 'Teaching / Education / Training',            subs: ['School Teacher', 'Lecturer / Professor', 'Corporate Trainer', 'Curriculum Design', 'EdTech'] },
  telecom:          { label: 'Telecom / Communications Engineering',       subs: ['RF Engineer', 'Telecom Operations', '5G / LTE', 'Network Planning', 'Tower Operations'] },
  transport:        { label: 'Transport / Driving',                        subs: ['Fleet Management', 'Logistics Coordinator', 'Delivery / Courier', 'Dispatch', 'Commercial Driving'] },
  travel:           { label: 'Travel / Ticketing / Reservations',          subs: ['Travel Agent', 'Tour Operations', 'Airline Ticketing', 'Visa Processing', 'Destination Management'] },
};

module.exports = { INDUSTRY_SUBS };
